version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: book_api
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres123
        ports:
            - 5433:5432